apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-34uz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-34uz
    app.kubernetes.io/part-of: tkwch-fix-0075-0038-app
  name: devfile-sample-34uz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-34uz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-34uz
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0038-tenant/tkwch-fix-0075-0038-app/devfile-sample-34uz@sha256:d0751564259d71acc5b0d7dc11b450134e3e4c0272b9f300045cc446f5d3c5c0
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
